name: Trivy File Scan
on:
  push:
    branches: '**'     
  pull_request:
jobs:      
  FSbuild:
    name: FSScan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3      

      - name: Run Trivy vulnerability scanner in FS command
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scanners: 'vuln,secret,config'
          format: 'sarif'        
          output: 'trivy-fs-scan-results.sarif'
          severity: 'CRITICAL,HIGH'

          
      - name: Upload Trivy scan results as Artifact
        uses: actions/upload-artifact@v3
        with:  
          name: 'ScanResults.json'
          path: './trivy-fs-scan-results.sarif'

      - name: Upload Trivy scan results to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-fs-scan-results.sarif'
